"""analytics tables updated

Revision ID: 5b1bff723648
Revises: 8ea1b1029a96
Create Date: 2026-02-09 13:25:47.866312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1bff723648'
down_revision: Union[str, None] = '8ea1b1029a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_resignation', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('department', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('sub_department', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('designation', sa.String(), nullable=True))
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_column('employees', 'designation')
    op.drop_column('employees', 'sub_department')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'date_of_resignation')
    # ### end Alembic commands ###
