"""initial

Revision ID: 63e34ede6dd9
Revises: 20b51403f36c
Create Date: 2025-12-09 10:34:28.779176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e34ede6dd9'
down_revision: Union[str, None] = '20b51403f36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('l1_manager', sa.String(), nullable=True),
    sa.Column('l1_manager_code', sa.String(), nullable=True),
    sa.Column('l2_manager', sa.String(), nullable=True),
    sa.Column('l2_manager_code', sa.String(), nullable=True),
    sa.Column('hrbp_name', sa.String(), nullable=True),
    sa.Column('hrbp_code', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('joining_date', sa.String(), nullable=True),
    sa.Column('exit_date', sa.String(), nullable=True),
    sa.Column('survey_initiated_date', sa.String(), nullable=True),
    sa.Column('survey_submission_date', sa.String(), nullable=True),
    sa.Column('overall_sentiment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_analysis_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('raw_answers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
