"""added new column in employees table

Revision ID: 8461f5c0d3bb
Revises: 63e34ede6dd9
Create Date: 2025-12-10 11:49:14.543040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8461f5c0d3bb'
down_revision: Union[str, None] = '63e34ede6dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('date_of_resignation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'date_of_resignation')
    op.drop_column('employees', 'designation')
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###
