"""analytics tables added

Revision ID: 8ea1b1029a96
Revises: 
Create Date: 2026-02-09 12:50:10.966798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea1b1029a96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_detailed_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('employee_answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_detailed_reasons_category_name'), 'category_detailed_reasons', ['category_name'], unique=False)
    op.create_index(op.f('ix_category_detailed_reasons_department'), 'category_detailed_reasons', ['department'], unique=False)
    op.create_index(op.f('ix_category_detailed_reasons_id'), 'category_detailed_reasons', ['id'], unique=False)
    op.create_index(op.f('ix_category_detailed_reasons_month'), 'category_detailed_reasons', ['month'], unique=False)
    op.create_index(op.f('ix_category_detailed_reasons_year'), 'category_detailed_reasons', ['year'], unique=False)
    op.create_table('category_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('reason_name', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', 'department', 'reason_name', name='_cat_dept_month_uc')
    )
    op.create_index(op.f('ix_category_stats_department'), 'category_stats', ['department'], unique=False)
    op.create_index(op.f('ix_category_stats_id'), 'category_stats', ['id'], unique=False)
    op.create_table('department_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('total_exits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', 'department', name='_dept_month_uc')
    )
    op.create_index(op.f('ix_department_stats_department'), 'department_stats', ['department'], unique=False)
    op.create_index(op.f('ix_department_stats_id'), 'department_stats', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('l1_manager', sa.String(), nullable=True),
    sa.Column('l1_manager_code', sa.String(), nullable=True),
    sa.Column('l2_manager', sa.String(), nullable=True),
    sa.Column('l2_manager_code', sa.String(), nullable=True),
    sa.Column('hrbp_name', sa.String(), nullable=True),
    sa.Column('hrbp_code', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('joining_date', sa.String(), nullable=True),
    sa.Column('exit_date', sa.String(), nullable=True),
    sa.Column('survey_initiated_date', sa.String(), nullable=True),
    sa.Column('survey_submission_date', sa.String(), nullable=True),
    sa.Column('overall_sentiment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_analysis_json', sa.JSON(), nullable=True),
    sa.Column('exit_category', sa.String(), nullable=True),
    sa.Column('is_controllable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_exit_category'), 'analysis_reports', ['exit_category'], unique=False)
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('raw_answers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_exit_category'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_department_stats_id'), table_name='department_stats')
    op.drop_index(op.f('ix_department_stats_department'), table_name='department_stats')
    op.drop_table('department_stats')
    op.drop_index(op.f('ix_category_stats_id'), table_name='category_stats')
    op.drop_index(op.f('ix_category_stats_department'), table_name='category_stats')
    op.drop_table('category_stats')
    op.drop_index(op.f('ix_category_detailed_reasons_year'), table_name='category_detailed_reasons')
    op.drop_index(op.f('ix_category_detailed_reasons_month'), table_name='category_detailed_reasons')
    op.drop_index(op.f('ix_category_detailed_reasons_id'), table_name='category_detailed_reasons')
    op.drop_index(op.f('ix_category_detailed_reasons_department'), table_name='category_detailed_reasons')
    op.drop_index(op.f('ix_category_detailed_reasons_category_name'), table_name='category_detailed_reasons')
    op.drop_table('category_detailed_reasons')
    # ### end Alembic commands ###
